#!/usr/bin/env bash

init_paths=(
    "Workspace/Projects/cobrinhas/send-to-pocket-book/proxy-server"
    "Workspace/Projects/cobrinhas/instagram-story-tracker"
)

for path in "${init_paths[@]}"; do bash $path/init; done
