#!/usr/bin/env bash

init_paths=(
    "${HOME}/Workspace/Projects/cobrinhas/send-to-pocket-book/proxy-server"
    "${HOME}/Workspace/Projects/cobrinhas/instagram-story-tracker"
)

for path in "${init_paths[@]}"; do (cd $path; bash init); done
